### PR TITLE
chore: move from koa-generic-session to koa-session (#35)

### PR DESCRIPTION
**Pull request by ohjames**

### CODE REVIEW

**Comment by wong2** [comment]
@niftylettuce @dead-horse please merge this

**Comment by smashercosmo** [comment]
@niftylettuce any ETA on publishing version with these changes?

**Comment by niftylettuce** [comment]
@smashercosmo 	see my comment here https://github.com/koajs/koa-redis/issues/35#issuecomment-571536410

**Comment by niftylettuce** [comment]
I am _not_ merging this right now because I don't recommend `koa-session` at the moment, since it does not support a `saveSession` method as similar to `koa-generic-session` currently does - which affects functionality when compared to `express-session`, which modifies session (saves) on `res.end` overwrite.

**Comment by smashercosmo** [comment]
@niftylettuce thx for explaination

**Pull request merged**
