### PR TITLE
[WIP] Replace koa-generic-session with koa-session

### LINKED ISSUE #35: koa-generic-session is deprecated
Would there be any interest in a PR that implements support for `koa-session`? It would require a big major version bump since it would be breaking. Potentially there could be support for both using a flag or arg detection maybe. I would be willing to do the work on this but only if it is likely to be merged. It also needs more discussion.

### PR DESCRIPTION
**Pull request by nicklaw5**
**Note:** This is a work in progress. I'm open to discussion for specific implementation whilst I continue to make minor changes and improvement to tests and test coverage.

Migrating from `koa-generic-session` to `koa-session` is a major breaking change. This implementation uses Node's `util.promisify` function for converting a callback-based function to a Promise-based one, which means Node v8+ is required.

These changes also:
- converted all generators to async/await functions
- dropped backward compatibility for `options.socket` and `options.pass`
- updated all existing tests and removed obsolete async-specific tests
- replaced `istanbul` with `nyc` to support ES6 syntax code coverage
- had `RedisStore` extend `EventEmitter`, since that is the preferred method when using class inheritance
- added `eslint` for linting

Closes #35

### CODE REVIEW

**Comment by nicklaw5** [comment]
@dead-horse @DaAwesomeP 
Is there any possibility of having one (or both) of you review  this?

**Comment by edevil** [comment]
Thanks for your work, I hope it gets merged.

**Comment by smashercosmo** [comment]
Is there anything I can do to help to get this merged?

**Comment by smashercosmo** [comment]
ping @dead-horse @DaAwesomeP

**Comment by niftylettuce** [comment]
@nicklaw5 could you please see latest v4.0.0 in master branch and submit a new PR?

**Comment by Max-Starling** [comment]
Any updates on this?

**Comment by nicklaw5** [comment]
I can possibly take a look at this over the weekend :slightly_smiling_face:

**Comment by smashercosmo** [comment]
friendly ping @nicklaw5

**Comment by nicklaw5** [comment]
My apologies, I haven't had the time to look at this. I don't see me having the time to look at it anytime soon either. Happy for someone else to continue on where I left off.

**Comment by ohjames** [comment]
Fix in https://github.com/koajs/koa-redis/pull/56 together with proper expiry support. Also replaced generators with async/await and added TypeScript support. Published as koa-redis-snowman. Happy to merge upstream.

**Pull request closed without merging**
