### PR TITLE
Support optional serialize and unserialize

### PR DESCRIPTION
**Pull request by Runrioter**
When I am restructuring some existing code that wrote by Java and PHP, I have a problem. Data in store was serialize or unserialize in Java/PHP Object serialization, so I want to make this repo support serialize/unserialize.

Please review it.

### CODE REVIEW

**Comment by DaAwesomeP** [comment]
@Runrioter Thank you! I really like this idea. Could you please add tests for `serialize` and `unserialize`? It can be something really simple (ex. adding some characters to the send of `JSON.stringify()` in `serialize` so that it will fail `JSON.parse()` unless it goes through `unserialize`).

**Comment by DaAwesomeP** [comment]
Thanks!

**Comment by Runrioter** [comment]
@DaAwesomeP  my pleasure

**Comment by Runrioter** [comment]
@DaAwesomeP  Can you release a patch version? I will use it in production.

**Comment by DaAwesomeP** [comment]
@Runrioter I'm going to wait a day or so to hear from #34. In the meantime, you can specify your fork as a source to NPM.

**Comment by DaAwesomeP** [comment]
@Runrioter I published v3.1.1.

**Pull request merged**
